# Site settings
author: Darius Stewart
title: Digital Darius
header-img: img/home-bg.png
email: darius.stewart31@gmail.com
copyright_name: Darius Stewart
description: > # this means to ignore newlines until "baseurl:"
  The coding wave
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  HopeDolo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
